
---


# must install openssh-server on new machine first, then copy ofer ssh key


- name: Update apt-get repo and cache.
  apt:
    update_cache: true

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: true

- name: install visual studio code.
  snap:
    name: code
    classic: true


- name: install ansible and linters and git.
  apt:
    pkg:
      - ansible
      - yamllint
      - ansible-lint
      - git
      - curl
      - python3
      - python3-pip
      - gkrellm
      - sshfs


- name: update python 3 alternatives
  command: "update-alternatives --install /usr/bin/python python /usr/bin/python3 1"
  register: pythonvar

- name: remove unwanted packages.
  apt:
    pkg:
      - thunderbird
      - libreoffice*
      - rhythmbox
    state: absent

- name: Clone a devops repo with separate git directory.
  git:
    repo: "{{ git_root }}/{{ devops_repo }}"
    dest: "/home/{{ user }}/{{ devops_repo }}"
    update: false

- name: Recursively change ownership of devops directory.
  file:
    path: "/home/{{ user }}/{{ devops_repo }}"
    state: directory
    recurse: true
    owner: "{{ user }}"

