---
# - include_role:
#     name: update_distro

- name: install yum utils.
  yum:
    name:
      - yum-utils
      - zip
      - unzip
    state: present

- name: install yum-config-mgr add repo docker.
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  become: true
  register: yum_var
  changed_when: yum_var.rc != 0

- name: remove runc
  yum:
    name: runc
    state: absent

- name:  install docker engine.
  yum:
    name:
      - docker-engine
#      - docker-ce-cli
 #     - containerd.io
#    nobest: false

- name: start docker service.
  systemd:
    name: docker.service
    enabled: true
    state: started

- name: setup user to run docker.
  command: usermod -a -G docker $USER
  register: user_var
  changed_when: user_var.rc !=0


# if needed to logout/log back in as user, run:
# - name: reset ssh connection to allow user changes to affect 'current login user'
#   meta: reset_connection
# http://docker-release-blue-prod.s3-website-us-east-1.amazonaws.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.4.6-3.1.el8.x86_64.rpm
# http://docker-release-blue-prod.s3-website-us-east-1.amazonaws.com/linux/centos/8/x86_64/stable/Packages/docker-ce-20.10.7-3.el8.x86_64.rpm
# http://docker-release-blue-prod.s3-website-us-east-1.amazonaws.com/linux/centos/8/x86_64/stable/Packages/docker-ce-cli-20.10.7-3.el8.x86_64.rpm
#echo "docker_user  ALL=(ALL)  NOPASSWD: /usr/bin/docker" >> /etc/sudoers
# echo "alias docker=\"sudo /usr/bin/docker\"" >> /home/docker_user/.bash_profile#


#dnf install -y dnf-utils zip unzip
#dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
#dnf remove -y runc
#dnf install -y docker-ce --nobest
# systemctl enable docker.service
# systemctl start docker.service
# sudo usermod -a -G docker $USER - logout and log back in

# Following is not needed but kept as alternative
# useradd docker_user
# echo "docker_user  ALL=(ALL)  NOPASSWD: /usr/bin/docker" >> /etc/sudoers
# echo "alias docker=\"sudo /usr/bin/docker\"" >> /home/docker_user/.bash_profile
# su - docker_user
#$ docker ps
#https://oracle-base.com/articles/linux/docker-install-docker-on-oracle-linux-ol8